scrape-configs:
  - job: cprofiler
    interval: 60s         # the interval for scrape profile data
    expiration: 168h      # the profile data expire time
    # enabled-profiles include: profile, mutex, heap, goroutine, allocs, block, threadcreate, trace, all
    # all : means all sample type except trace
    # if not config, the default is all
    enabled-profiles: [all, trace]
    path-profiles:
      profile: /debug/pprof/profile?seconds=10
      trace: /debug/pprof/trace?seconds=10
    target-configs:
      - application: cprofiler
        hosts:
          - 127.0.0.1:9000
        labels:
          env: dev